# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kayıp Sözlük
brief-intro: Aradığınız her şey bu sözlükte!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kayipsozluk.com" # the base hostname & protocol for your site

permalink: /:categories/:title/

# other links
twitter_username: 
facebook_username: 
email: kayipsozlukcom@gmail.com 
linkedIn_username: 
description_footer: 

duoshuo_shortname: #hygblog
disqus_shortname: kayip-sozluk

#baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-45024950-8

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: search/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 6
