# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

site_name: Kayıp Sözlük
title: Kayıp Sözlük
email: kayipsozlukcom@gmail.com
siteimage:
description: Aradığınız herşey bu sözlükte
news: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: :title
development: false

# Social Media Accounts
twitter_username: kayipsozluk
googleplus_url:
facebook_url:

# Disqus Setting
disqus: "kayip-sozluk"

# FeedBurner Setting
feedburner: "kayipsozluk"

# Build settings
markdown: kramdown
plugins: [jekyll-feed,jekyll-paginate,jekyll-paginate-multiple,jekyll-sitemap]

# Main paginate
paginate: 5

#Category paginate
paginate_multiple:
  - paginate: 10
    paginate_path: '/merak-edilenler/:num/'
    sub_dir: '/merak-edilenler'
  - paginate: 10
    paginate_path: '/sinema/:num/'
    sub_dir: '/sinema'
  - paginate: 10
    paginate_path: '/televizyon/:num/'
    sub_dir: '/televizyon'
  - paginate: 10
    paginate_path: '/tiyatro/:num/'
    sub_dir: '/tiyatro'
  - paginate: 10
    paginate_path: '/kitap/:num/'
    sub_dir: '/kitap'
  - paginate: 10
    paginate_path: '/teknoloji/:num/'
    sub_dir: '/teknoloji'
  - paginate: 10  
    paginate_path: '/tarih/:num/'
    sub_dir: '/tarih'
  - paginate: 10  
    paginate_path: '/psikoloji/:num/'
    sub_dir: '/psikoloji'
  - paginate: 10  
    paginate_path: '/saglikveyasam/:num/'
    sub_dir: '/saglikveyasam'